import type { CocktailCardModel } from './types';

export const MOCK_COCKTAILS: CocktailCardModel[] = [
  {
    id: 'mock-1',
    name: 'Mojito Royal',
    slug: 'mojito-royal',
    tags: ['Frais', 'Menthe', 'Citron'],
    difficulty: 'Facile',
    duration: '5 min',
    alcohol: true,
    description: "Le roi des cocktails d'ete.",
    image: null,
    variantOfId: null,
  },
  {
    id: 'mock-2',
    name: 'Virgin Colada',
    slug: 'virgin-colada',
    tags: ['Fruite', 'Coco', 'Ananas'],
    difficulty: 'Facile',
    duration: '3 min',
    alcohol: false,
    description: "Version sans alcool ultra-cremeuse.",
    image: null,
    variantOfId: null,
  },
  {
    id: 'mock-3',
    name: 'Old Fashioned',
    slug: 'old-fashioned',
    tags: ['Amer', 'Whisky', 'Classique'],
    difficulty: 'Moyen',
    duration: '8 min',
    alcohol: true,
    description: 'Le classique intemporel.',
    image: null,
    variantOfId: null,
  },
  {
    id: 'mock-4',
    name: 'Cosmopolitan',
    slug: 'cosmopolitan',
    tags: ['Vodka', 'Soiree'],
    difficulty: 'Moyen',
    duration: '5 min',
    alcohol: true,
    description: 'Le cocktail iconique.',
    image: null,
    variantOfId: null,
  },
  {
    id: 'mock-5',
    name: 'Spritz',
    slug: 'spritz',
    tags: ['Aperitif', 'Petillant'],
    difficulty: 'Facile',
    duration: '4 min',
    alcohol: true,
    description: "L'apero italien.",
    image: null,
    variantOfId: null,
  },
  {
    id: 'mock-6',
    name: 'Limonade Maison',
    slug: 'limonade-maison',
    tags: ['Citron', 'Sans alcool'],
    difficulty: 'Facile',
    duration: '4 min',
    alcohol: false,
    description: 'Simple et efficace.',
    image: null,
    variantOfId: null,
  },
];
